### ISSUE TITLE
install.packages() can't see mavericks/contrib/3.2/datapackages_0.9.0.9002.tgz

### ISSUE THREAD

**Issue by gothub** [NCEAS/drat#1]
Both PKIplus and redland can be installed from the same drat repo dir: ./bin/macosx/mavericks/contrib/3.2, but for some reason 'datapackage' isn't found. The PACKAGE
file and the file name for the datapackage bin build look fine, so I'm not sure what the problem is.

Once I've determined that this isn't just a config problem, I'll log an issue in the drat repo for this.

**Comment by mbjones** [comment]
@sbpcs59 There were some issues described in [drat issue 20](https://github.com/eddelbuettel/drat/issues/20) with getting the right location for packages in drat for different mac os x versions.  I worked on a patch with @eddelbuettel, which I think was released in a newer version of drat.  Maybe it was put there with an earlier version? Can we confirm everything is in the right place?

**Comment by gothub** [comment]
@mbjones For some reason the datapackage binary build is producing a DESCRIPTION file with the line

```
Built: R 3.2.2; ; 2015-09-15 17:41:46 UTC; unix
```

whereas other packages such as PKIplus produce a binary build with a DESCRIPTION file with the line

```
Built: R 3.2.2; x86_64-apple-darwin13.4.0; 2015-09-15 17:36:18 UTC; unix
```

which I think is confusing drat. I'll look into the datapackage build further.

**Comment by mbjones** [comment]
Oh, @sbpcs59 -- that's because datapackage has no C code itself, so its a source package and doesn't need platform-specific binaries.  So, it goes in a different location.  There's still something wrong, but the Built line is probably correct.

**Comment by gothub** [comment]
@mbjones -- yes, that makes sense, as then there is no binary dependency tying the package to
an OS version. BTW, I tried installing datapackage again and it is now working:

```
 library(drat)
> addRepo("NCEAS")
> install.packages("datapackage")
trying URL 'http://NCEAS.github.io/drat/bin/macosx/mavericks/contrib/3.2/datapackage_0.9.0.9002.tgz'
Content type 'application/octet-stream' length 217852 bytes (212 KB)
```

I think it makes sense to have these "no compiled code" packages inserted into the OS version specific
directories, as then the user doesn't have to know that they need to install a source distribution - but it is
a small bit of extra work for the package authors. FYI: the insertPackage() call prints out:

```
Note: Non-binary OS X package will be installed in Mavericks path.
```
